name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and test backend
      run: |
        cd backend
        docker build -t taskflow-backend .
        docker run -d --name test-backend -p 5000:5000 taskflow-backend
        sleep 15  # Ждём запуска Flask
        curl -f http://localhost:5000/health || exit 1
        docker stop test-backend
        docker rm test-backend

    - name: Build frontend
      run: |
        cd frontend
        docker build -t taskflow-frontend .

    - name: Run full system with Docker Compose
      run: |
        docker compose up -d
        sleep 30
        curl -f http://localhost:5000/health || exit 1
        curl -f http://localhost:8080 || exit 1
        docker compose down

