name: CI Pipeline for TaskFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # УДАЛЯЕМ блок "Build and test backend" — он нам не нужен!

    - name: Build frontend
      run: |
        echo "📦 Building frontend image..."
        cd frontend
        docker build -t taskflow-frontend .
        echo "✅ Frontend image built successfully"

    - name: Run full system with Docker Compose
      run: |
        echo "🐳 Starting full system with Docker Compose..."
        docker compose up -d

        echo "⏳ Waiting 60 seconds for all services to initialize..."
        sleep 60  # Даём больше времени — GitHub Actions медленнее

        echo "✅ Checking backend health (/health)..."
        if curl -f http://localhost:5000/health; then
          echo "💚 Backend is responding"
        else
          echo "❌ Backend is NOT responding"
          docker compose logs backend
          exit 1
        fi

        echo "✅ Checking frontend availability..."
        if curl -f http://localhost:8080; then
          echo "💚 Frontend is responding"
        else
          echo "❌ Frontend is NOT responding"
          docker compose logs frontend
          exit 1
        fi

        echo "✅ FULL SYSTEM IS RUNNING SUCCESSFULLY!"
        echo "🛑 Stopping all containers..."
        docker compose down
